import Image from "next/image";
import { IconArrowRight, IconCheck, IconChevronDown, IconClock, IconFlask2, IconHeartHandshake, IconMapPin, IconMenu2, IconPhone, IconTruckDelivery } from "@tabler/icons-react";

const specialties = [
  ["Pain management", "Tailored dosage forms prescribed around individual needs.", "01"],
  ["Pediatric", "Child-friendly formats and flavours, when appropriate.", "02"],
  ["Veterinary", "Customized medication options for pets of many shapes and sizes.", "03"],
  ["Hormone therapy", "Precisely prepared formulations in collaboration with prescribers.", "04"],
  ["Dermatology", "Specialized topical preparations for individual treatment plans.", "05"],
  ["Palliative care", "Personalized dosage forms to support comfort and care.", "06"],
];

const steps = [
  ["Talk with your provider", "Your healthcare professional determines whether a compounded prescription is appropriate."],
  ["Send your prescription", "Your prescription is securely submitted to the MEDS pharmacy team."],
  ["We prepare it", "Our team prepares the prescribed formulation in our specialized laboratory."],
  ["Pickup or delivery", "Collect your medication at Kingsway or ask about available delivery options."],
];

const faqs = [
  ["What is a compounding pharmacy?", "A compounding pharmacy prepares customized medication formulations based on a valid prescription when a standard commercial option may not meet a patient’s individual needs."],
  ["Do I need a prescription?", "Yes. Compounded prescription medications require a prescription from an authorized healthcare professional."],
  ["Can you make medication for children or pets?", "MEDS works with prescribers on pediatric and veterinary formulations, including alternative dosage forms and flavours where appropriate."],
  ["Do you offer delivery?", "Delivery options are available. Call the pharmacy team to confirm timing and availability for your prescription and location."],
];

function Logo() { return <a className="logo" href="#top" aria-label="MEDS home"><span>MEDS</span><small>Canadian Compounding Pharmacy</small></a>; }
function ArrowLink({ children, href="#contact" }: {children: React.ReactNode; href?: string}) { return <a className="arrow-link" href={href}>{children}<IconArrowRight size={18}/></a>; }

export default function Home() {
  return <>
    <a className="skip" href="#main">Skip to content</a>
    <div className="utility"><div className="container utility-inner"><span><IconMapPin size={15}/>Kingsway · Toronto</span><a href="tel:+14162393566"><IconPhone size={15}/>(416) 239-3566</a><span><IconClock size={15}/>Mon–Fri 9–7</span></div></div>
    <header id="top"><div className="container nav"><Logo/><nav aria-label="Main navigation"><a href="#compounding">Compounding</a><a href="#specialties">Specialties</a><a href="#process">How it works</a><a href="#about">About</a><a href="#location">Location</a></nav><a className="button button-small" href="#contact">Refill prescription</a><button className="menu" aria-label="Open menu"><IconMenu2/></button></div></header>
    <main id="main">
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Canadian compounding pharmacy · Toronto</p><h1>Medication made for <em>you.</em></h1><p className="lede">Customized medication solutions prepared around your individual needs by experienced compounding pharmacists in Toronto’s Kingsway community.</p><div className="actions"><a className="button" href="#contact">Speak with a pharmacist<IconArrowRight size={19}/></a><a className="text-button" href="#compounding">Explore compounding</a></div><div className="hero-proof"><div><strong>Since 1975</strong><span>Serving Toronto</span></div><div><strong>Specialized</strong><span>Compounding laboratory</span></div></div></div><div className="hero-media"><Image src="/images/compounding-lab.png" alt="A compounding pharmacist preparing a customized formulation in a laboratory" fill priority sizes="(max-width: 800px) 100vw, 50vw"/><div className="media-note"><IconHeartHandshake/><span><b>Care, made personal.</b>Pharmacist-led guidance</span></div></div></div></section>
      <section className="trust"><div className="container trust-grid"><span><IconCheck/>Established compounding experience</span><span><IconFlask2/>Specialized laboratory</span><span><IconTruckDelivery/>Delivery options available</span><span><IconMapPin/>Toronto based</span></div></section>
      <section className="section intro" id="compounding"><div className="container intro-grid"><div><p className="eyebrow">Why compounding?</p><h2>Sometimes one-size-fits-all medication <em>doesn’t fit.</em></h2></div><div><p className="large-copy">Compounding allows a pharmacist to prepare a medication around the specific prescription—adjusting its strength, dosage form, ingredients or flavour where appropriate.</p><p>Every formulation begins with a prescriber’s direction and is prepared with care by our pharmacy team.</p><ArrowLink>Talk with our pharmacy team</ArrowLink></div></div><div className="container benefit-row">{[["Dosage","Customized strengths"],["Form","Alternative dosage forms"],["Ingredients","Prescription-led adjustments"],["Flavour","Easier administration"]].map(([a,b],i)=><div className="benefit" key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></div>)}</div></section>
      <section className="section specialties" id="specialties"><div className="container"><div className="section-head"><div><p className="eyebrow light">Areas of expertise</p><h2>Compounding for different needs.</h2></div><p>We collaborate with patients and healthcare professionals across a broad range of specialized care.</p></div><div className="specialty-grid">{specialties.map(([title,desc,n],i)=><article className={`specialty specialty-${i+1}`} key={title}><span>{n}</span><div><h3>{title}</h3><p>{desc}</p><ArrowLink>Explore {title.toLowerCase()}</ArrowLink></div></article>)}</div></div></section>
      <section className="section process" id="process"><div className="container"><div className="center-head"><p className="eyebrow">From prescription to preparation</p><h2>Clear steps. Personal care.</h2><p>Not sure how compounding works? Our team keeps the process simple.</p></div><div className="steps">{steps.map(([title,desc],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><div className="step-dot"/><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section className="section story" id="about"><div className="container story-grid"><div className="story-photo"><Image src="/images/compounding-lab.png" alt="Inside the MEDS compounding laboratory" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="story-copy"><p className="eyebrow light">Why MEDS</p><h2>Compounding isn’t simply another service we added.</h2><p className="story-lede">It’s something we’ve specialized in for decades.</p><p>Since 1975, MEDS has served Toronto patients requiring specialized medications with the care and familiarity of a neighbourhood pharmacy.</p><ul>{["Pharmacist-led consultation","Collaboration with prescribers","Specialized compounding laboratory","Pickup and delivery options"].map(x=><li key={x}><IconCheck/>{x}</li>)}</ul><ArrowLink>Discover our story</ArrowLink></div></div></section>
      <section className="section pathways"><div className="container pathway-grid"><article><span>For patients</span><h2>Questions about a compounded prescription?</h2><p>Our pharmacy team can help you understand the next step.</p><ArrowLink>Talk to MEDS</ArrowLink></article><article><span>For healthcare professionals</span><h2>A compounding partner for your patients.</h2><p>Discuss formulations, prescriptions and patient-specific needs with our team.</p><ArrowLink>Prescriber information</ArrowLink></article></div></section>
      <section className="section faq"><div className="container faq-grid"><div><p className="eyebrow">Frequently asked</p><h2>Good questions deserve clear answers.</h2><p>For advice specific to your prescription, speak directly with a pharmacist.</p><a className="button secondary" href="tel:+14162393566">Call the pharmacy</a></div><div className="accordion">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<IconChevronDown/></summary><p>{a}</p></details>)}</div></div></section>
      <section className="section location" id="location"><div className="container location-grid"><div className="map-art"><div className="map-lines"/><span className="map-pin"><IconMapPin/></span><div className="map-label"><b>MEDS Kingsway</b><small>2920 Bloor St W</small></div></div><div><p className="eyebrow">Visit us</p><h2>Your neighbourhood compounding pharmacy.</h2><address>2920 Bloor Street West<br/>Toronto, Ontario</address><div className="hours"><span>Monday–Friday <b>9:00 AM–7:00 PM</b></span><span>Saturday <b>10:00 AM–2:00 PM</b></span><span>Sunday <b>Closed</b></span></div><div className="actions"><a className="button" href="https://maps.google.com/?q=2920+Bloor+Street+West+Toronto">Get directions</a><a className="text-button" href="tel:+14162393566">(416) 239-3566</a></div></div></div></section>
      <section className="final-cta" id="contact"><div className="container"><p className="eyebrow light">We’re here to help</p><h2>Have a question about a compounded prescription?</h2><p>Speak with our pharmacy team and understand your next step.</p><a className="button pale" href="tel:+14162393566"><IconPhone/>Call (416) 239-3566</a></div></section>
    </main>
    <footer><div className="container footer-grid"><Logo/><p>Personalized pharmacy care in Toronto’s Kingsway community since 1975.</p><div><a href="#compounding">Compounding</a><a href="#specialties">Specialties</a><a href="#location">Location</a></div><div><b>MEDS Kingsway</b><span>2920 Bloor Street West</span><a href="tel:+14162393566">(416) 239-3566</a></div></div><div className="container footer-bottom"><span>© 2026 MEDS Canadian Compounding Pharmacy</span><span>Clinical content requires pharmacist approval before publication.</span></div></footer>
    <div className="mobile-bar"><a href="tel:+14162393566"><IconPhone/>Call pharmacy</a><a href="#contact">Refill RX<IconArrowRight/></a></div>
  </>;
}
